### ISSUE TITLE
How to use it with Webpack?

### ISSUE THREAD

**Issue by pablo-sg-pacheco** [yunsii/unplugin-svg-sprite#10]
I know you have added a simple example but it doesn't work for me.

In general, Webpack plugins start with the `new` keyword. Example:

```js
new MiniCssExtractPlugin({
    filename: 'css/[name].css',
}),
```

And not with:
```js
require('unplugin-svg-sprite/webpack')
```

When I try your example I get the error:

```
TypeError: require(...) is not a function
```

**Comment by yunsii** [comment]
`require` function is Node.js core function for module resolution, this error is weired. Please provide a minimal reproduction demo for debug.

Moreover, if you use tailwindcss as a css framework, I recommend you can try to use svg icons by tailwind plugin by https://iconify.design/docs/usage/css/tailwind/#options

Also I create a tailwind plugin [tailwindcss-plugin-iconify](https://github.com/yunsii/tailwindcss-plugin-iconify) for more easy to use.

**Comment by yunsii** [comment]
closed as stale
