### ISSUE TITLE
How to only generate static with symbol?

### ISSUE THREAD

**Issue by nerdyman** [yunsii/unplugin-svg-sprite#12]
Hi,

Is it possible to only output dynamic _or_ static with only stack _or_ symbol? Ideally, I only want to render the static symbol sprite.

Also, is it possible to set a totally custom output path? I would like to render my static sprite to a custom path like `static/sprites/icons.svg`.

The current output looks like:

```
static/sprites/
├── dynamic
│   └── symbol
│       ├── icons-stack.svg
│       └── icons.svg
└── static
    └── symbol
        ├── icons-stack.svg
        └── icons.svg
```

Whereas I only want:

```
static/sprites/
└── icons.svg
```

Apologies if I missed this in the docs, I tried a few things like setting a custom `dest` and setting `sprites.stack` to `false` in the config but wasn't able to achieve the above.

**Comment by yunsii** [comment]
How about to process [some special nodes](https://stackoverflow.com/a/74173265/8335317) if so? You can confirm that your svg icons without these special nodes?

**Comment by yunsii** [comment]
Moreover, I think use svg icons in css is a better solution, you only want to use svg sprite?

**Comment by nerdyman** [comment]
Thanks for the quick reply @yunsii! Yeah I think a symbol sprite is what suites our needs best. All of our icons are monochrome, they use whatever the current colour of the parent element is. 

We're using the sprite in a React component and want it to be loaded in a dedicated SVG file over the network rather than embedding it in the page so it can be cached.

It essentially works like this:

```tsx
import spritePath from '@/sprites/icons.svg'; // converted to path string and cache busted by bundler.

export const Icon = ({ name, ...props }) => {
  return (
    <svg {...props}>
      <use href={`${spritePath}#${name}`} />
    </svg>
  );
};

// Usage
<Icon name="alert" />
```

I'm a bit of a noob in regards to sprites so I'm open to suggestions if there's a better way to do things 🙌 

Would the CSS sprite work here?

**Comment by yunsii** [comment]
I think you should read https://antfu.me/posts/icons-in-pure-css firstly, just use svg icons in pure css. You can use it with UnoCSS or TailwindCSS plugin.

**Comment by nerdyman** [comment]
Thanks @yunsii, much appreciated! I'll close the issue and see if CSS sprites would work for us.

**Comment by yunsii** [comment]
FYI, [icons-in-pure-css](https://antfu.me/posts/icons-in-pure-css) is a completely new tech, it is not CSS sprites.
